# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# User.create!(email: "Matt3@test.com", password: "password", password_confirmation: "password")

# Category.create!(name: "Cervical Enteroception", description: "Feeling into the structures of the cervical spine and surrounding areas. Experiential sensitization as the first step to holistic interventions. Building continuity in awareness of what is happening inside of us.", category_image_url: "https://openclipart.org/image/800px/282973" )
# Category.create!(name: "Cervical Proprioception", description: "Sensing where bodily structures are in space and in relation to one another. Differentiating from default expressions of posture and optimal posture. Building continuity in choosing new expressions of postural integrity.", category_image_url: "https://www.seti.org/sites/default/files/styles/original/public/2018-05/earth%26moon.jpg?itok=DeU5ETfA" )
# Category.create!(name: "Breathwork as the Basis for Neural Reconfiguration", description: "Any long lasting results in postural integrity come from working directly with the nervous system through gentle exploration of our inhalation and exhalation. There are numerous ways to utilize the breath to build awareness, mobilize the deepest structures of the body, and release tension. ", category_image_url: "https://upload.wikimedia.org/wikipedia/commons/0/0d/2313_The_Lung_Pleurea.jpg" )
# Category.create!(name: "Secondary Cervical Structures", description: "Moving from fixation on the localized point of symptoms to start to understand the network of connections that contribute to patterns of tension and integrity. First differentiate then explore continuity in actions of the shoulders, arms, and upper back.", category_image_url: "https://cdn2.picryl.com/photo/2007/12/30/muscle-posterior-973f63-1024.png" )
# Category.create!(name: "Tertiary Cervical Structures", description: "Expand an understanding of the localized network of patterning to a more global perspective of patterned tension. First differentiate then find continuity in expressions of the transverse abdominii, erector spinae groups, and lower trapezius.", category_image_url: "https://cdn2.picryl.com/photo/2021/09/19/transversus-abdominis-a61fe6-640.png" )
# Category.create!(name: "Jaw/Occiput Connections", description: "Compounded tension in the muscles of the jaw and temples are continuous with tension that accumulates at the base of the skull. A most powerful point of intervention and interface to create continuity in postural integrity. Explore the present state of the jaw as a feedback mechanism for overrall stress and tension.", category_image_url: "https://live.staticflickr.com/353/20156530380_f446cdec2a_b.jpg" )
# Category.create!(name: "Cervical Mobility", description: "The final stage in creating long term changes within patterns of the neck. Gentle mobilization including all previous steps of the process ensures we are safe and thorough in our holistic approach. Gently engage with the localized area of tension. Premature local intervention can create more harm than good and result in dependency on quick fixes.", category_image_url: "https://pixahive.com/wp-content/uploads/2021/02/Neck-Stretch-357299-pixahive.jpg" )

Exercise.create!(name: "Exercise Number 1", description: "From a relaxed starting position...", category_id: 22, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 2", description: "From a relaxed starting position...", category_id: 22, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 3", description: "From a relaxed starting position...", category_id: 22, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 4", description: "From a relaxed starting position...", category_id: 23, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 5", description: "From a relaxed starting position...", category_id: 23, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 6", description: "From a relaxed starting position...", category_id: 23, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 7", description: "From a relaxed starting position...", category_id: 24, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 8", description: "From a relaxed starting position...", category_id: 24, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 9", description: "From a relaxed starting position...", category_id: 24, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 10", description: "From a relaxed starting position...", category_id: 25, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 11", description: "From a relaxed starting position...", category_id: 25, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 12", description: "From a relaxed starting position...", category_id: 25, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 13", description: "From a relaxed starting position...", category_id: 26, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 14", description: "From a relaxed starting position...", category_id: 26, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 15", description: "From a relaxed starting position...", category_id: 26, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 16", description: "From a relaxed starting position...", category_id: 27, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 17", description: "From a relaxed starting position...", category_id: 27, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 18", description: "From a relaxed starting position...", category_id: 27, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 19", description: "From a relaxed starting position...", category_id: 28, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 20", description: "From a relaxed starting position...", category_id: 28, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")
Exercise.create!(name: "Exercise Number 21", description: "From a relaxed starting position...", category_id: 28, start_image_url: "https://live.staticflickr.com/3892/14764212321_b64f6cc5a0_b.jpg", end_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmHluMcLWTQ2_UDO56EjX4kL8j_WW2lwmJIw&usqp=CAU")


